// const baseUrl = window?.env?.VITE_BACKEND_URL || "http://localhost:8000";
const baseUrl = "";

const AvatarList = [
	"bear",
	"buffalo",
	"cat",
	"chicken",
	"dog",
	"egypt-cat",
	"fox",
	"giraffe",
	"gorilla",
	"hippopotamus",
	"koala",
	"man",
	"panda",
	"rabbit",
	"sea-lion",
	"walrus",
	"woman",
];

const lang = {
	en: {
		Change_Language: "Change Language",
		search: "Search",
		avatar: "Avatar",
		username: "Username",
		password: "Password",
		about: "About",
		old: "Old",
		new: "New",
		change: "Change",
		Create_Group: "Create Group",
		Group_Name: "Group Name",
		Admin: "Admin",
		Dismiss_as_Admin: "Dismiss as Admin",
		Remove_User: "Remove User",
		Members: "Members",
		Make_Admin: "Make Admin",
		Remove_User: "Remove User",
		Add_User: "Add User",
		Leave_Group: "Leave Group",
		Type_here: "Type here",
		Send: "Send",
		Home: "Home",
		About_Us: "About Us",
		Chat: "Chat",
		Chat_App: "LinkUp",
		Help_Center: "Help Center",
		Profile: "Profile",
		Logout: "Logout",
		LogIn: "LogIn",
		Key_Features: "Key Features",
		features: [
			{
				feat: "Intuitive Interface",
				desc: "<span class='text-sky-500'>User-friendly</span> interface designed to be <span className='text-sky-500'>easy to use</span> and navigate.",
			},
			{
				feat: "Instant Messaging",
				desc: "<span class='text-sky-500'>Real-time</span> messaging functionality for <span className='text-sky-500'>quick</span> communication.",
			},
			{
				feat: "Security Features",
				desc: "Robust <span class='text-sky-500'>security measures</span> to protect user data and ensure <span class='text-sky-500'>privacy</span>.",
			},
			{
				feat: "Customizable Settings",
				desc: "Ability to <span class='text-sky-500'>personalize settings</span> according to <span class='text-sky-500'>individual preferences</span> and needs.",
			},
		],
		How_It_Works: "How It Works",
		How_It_Works_explained:
			"Getting started with LinkUp is easy.Simply sign up, and start chatting! Invite your team members, friends, or family to join LinkUp and start collaborating instantly.",
		CopyRight: "Copyright © 2024 - All right reserved",
		Help_Center_msg:
			"Welcome to our Help Center! We're dedicated to helping you with any questions you may have and also thrilled to be part of your messaging journey!",
		Help_Center_input: "Tell us what we can help",
		Help_Center_input_button: "Submit",
		Home_title_1:
			"Experience seamless communication like never before with LinkUp.",
		Home_title_2: `Say goodbye to <span class="text-sky-500">endless email threads</span> and disjointed conversations. Say hello to <span class="text-sky-500">effortless collaboration </span> and meaningful connections.`,
		Home_button: "Get Started",
		Email: "Email",
		Password: "Password",
		Login_msg: "Don't have an account?",
		Login_title_1: "Login now!",
		Login_title_2:
			"Start chatting! Login to connect with others and explore new conversations.",
		Chat_Bot: "Chat Bot",
		Chat_Type: "Chat Type",
		Change: "Change",
		Avatar: "Avatar",
		Toggle: "Toggle",
		Delete_Account: "Delete Account",
		Signup: "Signup",
		Signup_msg: "Already have an account?",
		Signup_title_1: "Signup now!",
		Signup_title_2:
			"Sign up now to join our friendly community! Connect with others and start chatting instantly.",
		Signup_dialog_title: "Registration Successful!",
		Signup_dialog_msg:
			"Congratulations on successfully joining our chat community! Your journey starts here. Hit the button below to log in and start chatting away!",
		Group_Description: "Group Description",
		Change_Group_About: "Change Group About",
		Change_Group_About_msg: "Should be less than 60 letters",
		Delete_Group: "Delete Group",
		ChangeProfile_msg: "Should be less than 30 letters",
		username_required: "username required",
		username_too_long: "username is too long",
		email_required: "email required",
		email_invalid: "invalid email",
		password_required: "password required",
		password_too_short: "password is too short",
		password_invalid: "invalid password",
		old_password_required: "old password required",
		about_required: "about required",
		about_too_long: "about is too long",
	},
	hindi: {
		Change_Language: "भाषा बदलें",
		search: "खोज",
		avatar: "अवतार",
		username: "उपयोगकर्ता नाम",
		password: "पासवर्ड",
		about: "विवरण",
		old: "पुराना",
		new: "नया",
		change: "परिवर्तन",
		Create_Group: "समूह बनाएं",
		Group_Name: "समूह का नाम",
		Admin: "व्यवस्थापक",
		Dismiss_as_Admin: "व्यवस्थापक के रूप में छोड़ें",
		Remove_User: "उपयोगकर्ता को निकालें",
		Members: "सदस्य",
		Make_Admin: "व्यवस्थापक बनाए",
		Remove_User: "उपयोगकर्ता को निकालें",
		Add_User: "उपयोगकर्ता जोड़ें",
		Leave_Group: "समूह छोड़ें",
		Type_here: "यहाँ टाइप करें",
		Send: "भेजें",
		Home: "घर",
		About_Us: "हमारे बारे में",
		Chat: "चैट",
		Help_Center: "सहायता केंद्र",
		Profile: "प्रोफ़ाइल",
		Logout: "लॉग आउट",
		LogIn: "लॉग इन",
		Key_Features: "विशेषताएं",
		features: [
			{
				feat: "सहज इंटरफ़ेस",
				desc: "<span class='text-sky-500'>उपयोगकर्ता-अनुकूल</span> इंटरफ़ेस को <span class='text-sky-500'>उपयोग में आसान</span> और नेविगेट करने के लिए डिज़ाइन किया गया है।",
			},
			{
				feat: "त्वरित संदेश सेवा",
				desc: "<span class='text-sky-500'>वास्तविक समय</span> संदेश सेवा कार्यक्षमता <span class='text-sky-500'>त्वरित</span> संचार के लिए।",
			},
			{
				feat: "सुरक्षा सुविधाएँ",
				desc: "उपयोगकर्ता डेटा की सुरक्षा और <span class='text-sky-500'>गोपनीयता</span> सुनिश्चित करने के लिए मजबूत <span class='text-sky-500'>सुरक्षा उपाय</span>।",
			},
			{
				feat: "अनुकूलन योग्य सेटिंग्स",
				desc: "<span class='text-sky-500'>व्यक्तिगत प्राथमिकताओं</span> और जरूरतों के अनुसार <span class='text-sky-500'>सेटिंग्स को वैयक्तिकृत करने</span> की क्षमता।",
			},
		],
		How_It_Works: "यह काम किस प्रकार करता है",
		How_It_Works_explained:
			"LinkUp के साथ शुरुआत करना आसान है। बस साइन अप करें, और चैट करना शुरू करें! LinkUp से जुड़ने के लिए अपनी टीम के सदस्यों, दोस्तों या परिवार को आमंत्रित करें और तुरंत सहयोग करना शुरू करें।",
		CopyRight: "कॉपीराइट © 2024 - सर्वाधिकार सुरक्षित",
		Help_Center_msg:
			"हमारे सहायता केंद्र में आपका स्वागत है! हम आपके किसी भी प्रश्न में आपकी सहायता करने के लिए समर्पित हैं और आपकी संदेश यात्रा का हिस्सा बनकर भी रोमांचित हैं!",
		Help_Center_input: "हमें बताएं कि हम क्या मदद कर सकते हैं",
		Help_Center_input_button: "जमा करें",
		Home_title_1: "LinkUp के साथ पहले जैसा सहज संचार अनुभव करें।",
		Home_title_2: `<span class="text-sky-500">अंतहीन ईमेल थ्रेड्स</span> और असंबद्ध वार्तालापों को अलविदा कहें। <span class="text-sky-500">सहज सहयोग </span> और सार्थक कनेक्शन को नमस्ते कहें।`,
		Home_button: "चालू करे",
		Email: "ईमेल",
		Password: "पासवर्ड",
		Login_msg: "कोई खाता नहीं है?",
		Login_title_1: "अभी लॉगिन करें!",
		Login_title_2:
			"चैटिंग शुरू करें! दूसरों से जुड़ने और नई बातचीत तलाशने के लिए लॉगिन करें।",
		Chat_Bot: "चैट बॉट",
		Chat_Type: "चैट प्रकार",
		Change: "बदलें",
		Avatar: "अवतार",
		Toggle: "टॉगल",
		Delete_Account: "खाता हटाएँ",
		Signup: "साइन अप करें",
		Signup_msg: "क्या आपके पास पहले से ही एक खाता है?",
		Signup_title_1: "अभी साइनअप करें!",
		Signup_title_2:
			"हमारे मित्रवत समुदाय में शामिल होने के लिए अभी साइन अप करें! दूसरों से जुड़ें और तुरंत चैट करना शुरू करें।",
		Signup_dialog_title: "पंजीकरण सफल!",
		Signup_dialog_msg:
			"हमारे चैट समुदाय में सफलतापूर्वक शामिल होने पर बधाई! आपकी यात्रा यहां शुरू होती है। लॉग इन करने और चैट शुरू करने के लिए नीचे दिए गए बटन को दबाएं!",
		Group_Description: "समूह विवरण",
		Change_Group_About: "समूह के बारे में बदलें",
		Change_Group_About_msg: "60 अक्षरों से कम होना चाहिए",
		Delete_Group: "समूह हटाएँ",
		ChangeProfile_msg: "30 अक्षरों से कम होना चाहिए",
		username_required: "उपयोगकर्ता नाम आवश्यक",
		username_too_long: "उपयोगकर्ता नाम बहुत लंबा है",
		email_required: "ईमेल आवश्यक",
		email_invalid: "अमान्य ईमेल",
		password_required: "पासवर्ड आवश्यक",
		password_too_short: "पासवर्ड बहुत छोटा है",
		password_invalid: "अमान्य पासवर्ड",
		old_password_required: "पुराना पासवर्ड आवश्यक",
		about_required: "विवरण आवश्यक",
		about_too_long: "विवरण बहुत लंबा है",
	},
	pjb: {
		Change_Language: "ਭਾਸ਼ਾ ਬਦਲੋ",
		search: "ਖੋਜ",
		avatar: "ਅਵਤਾਰ",
		username: "ਉਪਭੋਗਤਾ ਨਾਮ",
		password: "ਪਾਸਵਰਡ",
		about: "ਬਾਰੇ",
		old: "ਪੁਰਾਣਾ",
		new: "ਨਵਾਂ",
		change: "ਬਦਲੋ",
		Create_Group: "ਗਰੁੱਪ ਬਣਾਓ",
		Group_Name: "ਸਮੂਹ ਦਾ ਨਾਮ",
		Admin: "ਐਡਮਿਨ",
		Dismiss_as_Admin: "ਐਡਮਿਨ ਵਜੋਂ ਖਾਰਜ ਕਰੋ",
		Remove_User: "ਉਪਭੋਗਤਾ ਹਟਾਓ",
		Members: "ਮੈਂਬਰ",
		Make_Admin: "ਐਡਮਿਨ ਬਣਾਓ",
		Remove_User: "ਉਪਭੋਗਤਾ ਹਟਾਓ",
		Add_User: "ਉਪਭੋਗਤਾ ਸ਼ਾਮਲ ਕਰੋ",
		Leave_Group: "ਗਰੁੱਪ ਛੱਡੋ",
		Type_here: "ਇੱਥੇ ਟਾਈਪ ਕਰੋ",
		Send: "ਭੇਜੋ",
		Home: "ਘਰ",
		About_Us: "ਸਾਡੇ ਬਾਰੇ",
		Chat: "ਚੈਟ",
		Help_Center: "ਮਦਦ ਕੇਂਦਰ",
		Profile: "ਪ੍ਰੋਫਾਈਲ",
		Logout: "ਲੌਗਆਉਟ",
		LogIn: "ਲੌਗਇਨ",
		Key_Features: "ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
		features: [
			{
				feat: "ਅਨੁਭਵੀ ਇੰਟਰਫੇਸ",
				desc: "<span class='text-sky-500'>ਉਪਭੋਗਤਾ-ਅਨੁਕੂਲ</span> ਇੰਟਰਫੇਸ ਨੂੰ <span className='text-sky-500'>ਵਰਤਣ ਵਿੱਚ ਆਸਾਨ</span> ਅਤੇ ਨੈਵੀਗੇਟ ਕਰਨ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤਾ ਗਿਆ ਹੈ।",
			},
			{
				feat: "ਤਤਕਾਲ ਸੁਨੇਹਾ",
				desc: "<span className='text-sky-500'>ਤੁਰੰਤ</span> ਸੰਚਾਰ ਲਈ <span class='text-sky-500'>ਰੀਅਲ-ਟਾਈਮ</span> ਮੈਸੇਜਿੰਗ ਕਾਰਜਕੁਸ਼ਲਤਾ।",
			},
			{
				feat: "ਸੁਰੱਖਿਆ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
				desc: "ਉਪਭੋਗਤਾ ਡੇਟਾ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰਨ ਅਤੇ <span class='text-sky-500'>ਗੋਪਨੀਯਤਾ</span> ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਣ ਲਈ ਮਜ਼ਬੂਤ ​<span class='text-sky-500'>ਸੁਰੱਖਿਆ ਉਪਾਅ</span>।",
			},
			{
				feat: "ਕਸਟਮਾਈਜ਼ ਕਰਨ ਯੋਗ ਸੈਟਿੰਗ",
				desc: "<span class='text-sky-500'>ਵਿਅਕਤੀਗਤ ਤਰਜੀਹਾਂ</span> ਅਤੇ ਲੋੜਾਂ ਅਨੁਸਾਰ <span class='text-sky-500'>ਸੈਟਿੰਗਾਂ ਨੂੰ ਵਿਅਕਤੀਗਤ ਬਣਾਉਣ</span> ਦੀ ਸਮਰੱਥਾ।",
			},
		],
		How_It_Works: "ਕਿਦਾ ਚਲਦਾ",
		How_It_Works_explained:
			"LinkUp ਨਾਲ ਸ਼ੁਰੂਆਤ ਕਰਨਾ ਆਸਾਨ ਹੈ। ਬਸ ਸਾਈਨ ਅੱਪ ਕਰੋ, ਅਤੇ ਚੈਟਿੰਗ ਸ਼ੁਰੂ ਕਰੋ! LinkUp ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਣ ਲਈ ਆਪਣੀ ਟੀਮ ਦੇ ਮੈਂਬਰਾਂ, ਦੋਸਤਾਂ ਜਾਂ ਪਰਿਵਾਰ ਨੂੰ ਸੱਦਾ ਦਿਓ ਅਤੇ ਤੁਰੰਤ ਸਹਿਯੋਗ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ।",
		CopyRight: "ਕਾਪੀਰਾਈਟ © 2024 - ਸਾਰੇ ਅਧਿਕਾਰ ਰਾਖਵੇਂ ਹਨ",
		Help_Center_msg:
			"ਸਾਡੇ ਮਦਦ ਕੇਂਦਰ ਵਿੱਚ ਸੁਆਗਤ ਹੈ! ਅਸੀਂ ਤੁਹਾਡੇ ਕਿਸੇ ਵੀ ਸਵਾਲ ਵਿੱਚ ਤੁਹਾਡੀ ਮਦਦ ਕਰਨ ਲਈ ਸਮਰਪਿਤ ਹਾਂ ਅਤੇ ਤੁਹਾਡੇ ਮੈਸੇਜਿੰਗ ਸਫ਼ਰ ਦਾ ਹਿੱਸਾ ਬਣਨ ਲਈ ਰੋਮਾਂਚਿਤ ਵੀ ਹਾਂ!",
		Help_Center_input: "ਸਾਨੂੰ ਦੱਸੋ ਕਿ ਅਸੀਂ ਕੀ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ",
		Help_Center_input_button: "ਜਮ੍ਹਾਂ ਕਰੋ",
		Home_title_1: "LinkUp ਦੇ ਨਾਲ ਪਹਿਲਾਂ ਕਦੇ ਵੀ ਸਹਿਜ ਸੰਚਾਰ ਦਾ ਅਨੁਭਵ ਕਰੋ।",
		Home_title_2: `<span class="text-sky-500">ਬੇਅੰਤ ਈਮੇਲ ਥ੍ਰੈਡਸ</span> ਨੂੰ ਅਲਵਿਦਾ ਕਹੋ ਅਤੇ ਅਸੰਬੰਧਿਤ ਗੱਲਬਾਤ। <span class="text-sky-500">ਸਹਿਯੋਗ ਸਹਿਯੋਗ </span> ਅਤੇ ਅਰਥਪੂਰਨ ਕਨੈਕਸ਼ਨਾਂ ਨੂੰ ਹੈਲੋ ਕਹੋ।`,
		Home_button: "ਸ਼ੁਰੂ ਕਰੋ",
		Email: "ਈ - ਮੇਲ",
		Password: "ਪਾਸਵਰਡ",
		Login_msg: "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਖਾਤਾ ਨਹੀਂ ਹੈ?",
		Login_title_1: "ਹੁਣੇ ਲੌਗਇਨ ਕਰੋ!",
		Login_title_2:
			"ਚੈਟਿੰਗ ਸ਼ੁਰੂ ਕਰੋ! ਦੂਜਿਆਂ ਨਾਲ ਜੁੜਨ ਲਈ ਲੌਗਇਨ ਕਰੋ ਅਤੇ ਨਵੀਆਂ ਗੱਲਾਂਬਾਤਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ।",
		Chat_Bot: "ਚੈਟ ਬੋਟ",
		Chat_Type: "ਗੱਲਬਾਤ ਦੀ ਕਿਸਮ",
		Change: "ਬਦਲੋ",
		Avatar: "ਅਵਤਾਰ",
		Toggle: "ਟੌਗਲ ਕਰੋ",
		Delete_Account: "ਖਾਤਾ ਮਿਟਾਓ",
		Signup: "ਸਾਇਨ ਅਪ",
		Signup_msg: "ਕੀ ਪਹਿਲਾਂ ਤੋਂ ਹੀ ਖਾਤਾ ਹੈ?",
		Signup_title_1: "ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ!",
		Signup_title_2:
			"ਸਾਡੇ ਦੋਸਤਾਨਾ ਭਾਈਚਾਰੇ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਣ ਲਈ ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ! ਦੂਜਿਆਂ ਨਾਲ ਜੁੜੋ ਅਤੇ ਤੁਰੰਤ ਚੈਟਿੰਗ ਸ਼ੁਰੂ ਕਰੋ।",
		Signup_dialog_title: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫਲ!",
		Signup_dialog_msg:
			"ਸਾਡੇ ਚੈਟ ਭਾਈਚਾਰੇ ਵਿੱਚ ਸਫਲਤਾਪੂਰਵਕ ਸ਼ਾਮਲ ਹੋਣ ਲਈ ਵਧਾਈਆਂ! ਤੁਹਾਡੀ ਯਾਤਰਾ ਇੱਥੇ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ। ਲੌਗ ਇਨ ਕਰਨ ਅਤੇ ਚੈਟਿੰਗ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਹੇਠਾਂ ਦਿੱਤੇ ਬਟਨ ਨੂੰ ਦਬਾਓ!",
		Group_Description: "ਸਮੂਹ ਵਰਣਨ",
		Change_Group_About: "ਬਦਲੋ ਗਰੁੱਪ ਬਾਰੇ",
		Change_Group_About_msg: "60 ਅੱਖਰਾਂ ਤੋਂ ਘੱਟ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ",
		Delete_Group: "ਗਰੁੱਪ ਨੂੰ ਮਿਟਾਓ",
		ChangeProfile_msg: "30 ਅੱਖਰਾਂ ਤੋਂ ਘੱਟ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ",
		username_required: "ਉਪਭੋਗਤਾ ਨਾਮ ਲੋੜੀਂਦਾ",
		username_too_long: "ਉਪਭੋਗਤਾ ਨਾਮ ਬਹੁਤ ਲੰਮਾ ਹੈ",
		email_required: "ਈਮੇਲ ਦੀ ਲੋੜ ਹੈ",
		email_invalid: "ਅਵੈਧ ਈਮੇਲ",
		password_required: "ਪਾਸਵਰਡ ਲੋੜੀਂਦਾ",
		password_too_short: "ਪਾਸਵਰਡ ਬਹੁਤ ਛੋਟਾ ਹੈ",
		password_invalid: "ਅਵੈਧ ਪਾਸਵਰਡ",
		old_password_required: "ਪੁਰਾਣਾ ਪਾਸਵਰਡ ਲੋੜੀਂਦਾ ਹੈ",
		about_required: "ਲੋੜੀਂਦੇ ਬਾਰੇ",
		about_too_long: "ਬਾਰੇ ਬਹੁਤ ਲੰਮਾ ਹੈ",
	},
	marathi: {
		Change_Language: "भाषा बदला",
		search: "शोधा",
		avatar: "अवतार",
		username: "वापरकर्तानाव",
		password: "पासवर्ड",
		about: "बद्दल",
		old: "जुन्या",
		new: "नवीन",
		change: "बदला",
		Create_Group: "गट तयार करा",
		Group_Name: "गटाचे नाव",
		Admin: "ॲडमिन",
		Dismiss_as_Admin: "प्रशासक म्हणून डिसमिस करा",
		Remove_User: "वापरकर्ता काढा",
		Members: "सदस्य",
		Make_Admin: "ॲडमिन करा",
		Remove_User: "वापरकर्ता काढा",
		Add_User: "वापरकर्ता जोडा",
		Leave_Group: "गट सोडा",
		Type_here: "येथे लिहा",
		Send: "पाठवा",
		Home: "मुख्यपृष्ठ",
		About_Us: "आमच्याबद्दल",
		Chat: "गप्पा",
		Help_Center: "मदत केंद्र",
		Profile: "प्रोफाइल",
		Logout: "बाहेर पडणे",
		LogIn: "लॉग इन",
		Key_Features: "महत्वाची वैशिष्टे",
		features: [
			{
				feat: "अंतर्ज्ञानी इंटरफेस",
				desc: "<span class='text-sky-500'>वापरकर्ता-अनुकूल</span> इंटरफेस <span className='text-sky-500'>वापरण्यास सुलभ</span> आणि नेव्हिगेट करण्यासाठी डिझाइन केलेले आहे.",
			},
			{
				feat: "इन्स्टंट मेसेजिंग",
				desc: "<span className='text-sky-500'>त्वरित</span> संवादासाठी <span class='text-sky-500'>रिअल-टाइम</span> मेसेजिंग कार्यक्षमता.",
			},
			{
				feat: "सुरक्षा वैशिष्ट्ये",
				desc: "वापरकर्ता डेटा संरक्षित करण्यासाठी आणि <span class='text-sky-500'>गोपनीयता</span> सुनिश्चित करण्यासाठी मजबूत <span class='text-sky-500'>सुरक्षा उपाय</span>.",
			},
			{
				feat: "सानुकूल करण्यायोग्य सेटिंग्ज",
				desc: "<span class='text-sky-500'>वैयक्तिक प्राधान्ये</span> आणि गरजांनुसार <span class='text-sky-500'>सेटिंग्ज वैयक्तिकृत</span> करण्याची क्षमता.",
			},
		],
		How_It_Works: "हे कसे कार्य करते",
		How_It_Works_explained:
			"LinkUp सह प्रारंभ करणे सोपे आहे. फक्त साइन अप करा आणि चॅटिंग सुरू करा! तुमच्या कार्यसंघ सदस्यांना, मित्रांना किंवा कुटुंबाला LinkUp मध्ये सामील होण्यासाठी आमंत्रित करा आणि त्वरित सहयोग सुरू करा.",
		CopyRight: "कॉपीराइट © 2024 - सर्व हक्क राखीव",
		Help_Center_msg:
			"आमच्या मदत केंद्रावर स्वागत आहे! तुमच्या कोणत्याही प्रश्नांसाठी आम्ही तुम्हाला मदत करण्यास समर्पित आहोत आणि तुमच्या संदेशन प्रवासाचा भाग होण्यासाठी आम्ही रोमांचित आहोत!",
		Help_Center_input: "आम्ही काय मदत करू शकतो ते आम्हाला सांगा",
		Help_Center_input_button: "प्रस्तुत करणे",
		Home_title_1:
			"LinkUp सह यापूर्वी कधीही नसलेल्या अखंड संप्रेषणाचा अनुभव घ्या.",
		Home_title_2: `<span class="text-sky-500">अंतहीन ईमेल थ्रेड्स</span> आणि असंबद्ध संभाषणांना गुडबाय म्हणा. <span class="text-sky-500">प्रयत्नहीन सहयोग </span> आणि अर्थपूर्ण कनेक्शनला नमस्कार म्हणा.`,
		Home_button: "सुरु करूया",
		Email: "ईमेल",
		Password: "पासवर्ड",
		Login_msg: "खाते नाही?",
		Login_title_1: "आता लॉगिन करा!",
		Login_title_2:
			"चॅटिंग सुरू करा! इतरांशी कनेक्ट होण्यासाठी लॉग इन करा आणि नवीन संभाषणे एक्सप्लोर करा.",
		Chat_Bot: "चॅट बॉट",
		Chat_Type: "गप्पा प्रकार",
		Change: "बदला",
		Avatar: "अवतार",
		Toggle: "टॉगल करा",
		Delete_Account: "खाते हटवा",
		Signup: "साइनअप करा",
		Signup_msg: "आधीपासूनच एक खाते आहे?",
		Signup_title_1: "आत्ताच नोंदणी करा!",
		Signup_title_2:
			"आमच्या मैत्रीपूर्ण समुदायात सामील होण्यासाठी आता साइन अप करा! इतरांशी कनेक्ट व्हा आणि झटपट चॅटिंग सुरू करा.",
		Signup_dialog_title: "नोंदणी यशस्वी!",
		Signup_dialog_msg:
			"आमच्या चॅट समुदायात यशस्वीरित्या सामील झाल्याबद्दल अभिनंदन! तुमचा प्रवास इथून सुरू होतो. लॉग इन करण्यासाठी खालील बटण दाबा आणि चॅटिंग सुरू करा!",
		Group_Description: "गट वर्णन",
		Change_Group_About: "बदला गट बद्दल",
		Change_Group_About_msg: "60 अक्षरांपेक्षा कमी असावे",
		Delete_Group: "गट हटवा",
		ChangeProfile_msg: "३० अक्षरांपेक्षा कमी असावे",
		username_required: "वापरकर्तानाव आवश्यक",
		username_too_long: "वापरकर्तानाव खूप मोठे आहे",
		email_required: "ईमेल आवश्यक",
		email_invalid: "अवैध ईमेल",
		password_required: "पासवर्ड आवश्यक",
		password_too_short: "पासवर्ड खूप लहान आहे",
		password_invalid: "अवैध पासवर्ड",
		old_password_required: "जुना पासवर्ड आवश्यक",
		about_required: "आवश्यकतेबद्दल",
		about_too_long: "बद्दल खूप लांब आहे",
	},
};
export { AvatarList, lang, baseUrl };
